document.addEventListener("DOMContentLoaded", function () {
    i18next.init(
      {
        lng: "en",
        debug: true,
        resources: {

            
          en: {
            translation: {
              inicionav: "Home",
              greeting: "About-us",
              farewell: "Services",
              procedure: "Procedure",
              medicalE: "Medical Exams",
              specialist: "Specialists",
              quotation: "Quotation",
              log: "Login",
              esthetic: "Esthetic-surgery",
              sugery: "With the aim of generating a better appearance in individuals, increasing self-esteem and self-confidence, at Esthetic Health we provide you with all the information about the procedures you may want to undergo. You will learn about benefits, specialists, and quotations. Remember the importance of thoroughly investigating the procedure to be performed and the professional who will provide the service. Here, you will find a reliable schedule to ensure that the intervention will be carried out by the best specialists.",
              dermatology: "Dermatology",
              dermatologyDes: "Medical specialty dedicated to the study, understanding, diagnosis, and treatment of all skin pathologies or conditions. At Esthetic Health, you will find the link to the best specialists to give your skin the best care, carrying out your procedures hand in hand with the best.",
              recovery: "Recovery",
              recoveryDes: "Meet here the professionals who will help ensure that your surgery receives the best postoperative care, providing you with the best attention so that you can recover more quickly and achieve the best results.",
              contactus: "Contact-Us",
              advisor: "Advisors",
              Sponsors: "Sponsors",
              ourprogam: "Our Program",
              registration: "Registration",
              gree: "We are a team of developers passionate about innovation and the pursuit of a positive impact on people who need help accessing safe services, choosing the best for them. Our purpose with Esthetic Health is to create a comprehensive platform where people can find and access the necessary and important information when they want to undergo a cosmetic intervention or dermatological procedure.",
              cod: "Coders Riwi",
              tel: "Phone",
              ourservice: "Our Services",
              ape: "Aesthetic Procedures in Medellín",
              ena: "In Esthetic Healt, we offer you a wide portfolio of services that will adjust to your needs, giving you the confidence to find the best specialist to perform your procedures.",
              proceDes: "We help you schedule an initial assessment appointment with one of the best general practitioners so that you can assess your health status and guide you through the procedure you wish to undergo.",
              medicalDes: "We provide you with complete information about the exams you need to undergo before choosing the procedure and their costs.",
              espeDes: "We provide you with the best information about surgeons, anesthesiologists, therapists, and nurses who will take care of you throughout the process.",
              care: "Care",
              mobilization: "1. The patient should mobilize. To have a good postoperative period, you should walk inside your home, always accompanied by a family member or nurse, from the moment you leave the clinic.",
              hydration: "2. Stay hydrated. You should drink water frequently, as well as herbal teas and diluted juices. Avoid tea and coffee.",
              diet: "3. Liquid or soft diet on the first day. During the first 24 hours after your plastic surgery, you should follow a diet based on broth, soups, non-acidic juices, gelatin, and herbal teas.",
              respiratory: "4. Perform respiratory exercises with an incentive spirometer for 5 continuous minutes, 4 times a day, during the first week of your postoperative period.",
              rest: "5. Try to rest during sleep.",
              medication: "6. Take your medications. Adhere to the prescribed medication regimen and schedule. This is essential to ensure results and reduce risks and potential complications.",
              dizziness: "7. When getting out of bed, you may experience dizziness. In this case, it is advisable to return to bed and lie down with your legs elevated. You will feel better in a few minutes.",
              bandage: "8. Do not remove bandages or dressings until your doctor authorizes it.",
              drain: "9. Do not wet the drains and/or wounds until your plastic surgeon instructs you to do so. Avoid getting them wet when bathing, and if they accidentally get wet, dry them thoroughly without removing the bandages or dressings.",
              sunprotection: "10. Avoid sun exposure to the operated area during the first 4 months after surgery.",
              sexualabs: "11. Avoid sexual intercourse during the first month of the postoperative period.",
              safemobi: "12. Move in the most comfortable and safe way. Avoid using a motorcycle or public transportation.",
              des: "In Esthetic Healt, you will find the best professionals who will assist you with your recovery process.",
              pie: "All copyright rights are reserved to Riwi - 2023.",
              face: "Face",
              nose: "Rhinoplasty",
              see: "See more",
              biche: "Cheek reduction",
              blefaro: "Eyelid surgery",
              lipo: "Chin liposuction",
              otoplas: "Ear surgery",
              body: "Body",
              lipo: "Liposuction",
              lipoEs: "Liposculpture",
              glu: "Gluteoplasty",
              cirba: "Bariatric surgery",
              abdom:  "Abdominoplasty",
              sen: "breasts",
              maum: "Breast augmentation",
              maur: "Reduction mammoplasty",
              mast: "Mastopexy",
              breco: "Breast reconstruction",
              ginecoma: "Gynecomastia",
              dermatological: "Dermatological",
              hyal: "Hyaluronic acid",
              botox: "Botox",
              eare: "Easy rejuvenation",
              peeling: "Peeling",
              acne: "Acne treatment",
              exapre: "Preoperative examinations",
              questo:"What tests are recommended before surgeries?",
              respono: "For procedures to be performed under anesthesia, a series of preoperative tests are required, which will indicate to the physician possible problems that could occur in the intervention and in turn determine the risk factors to be prevented. The tests should always be based on the individual evaluation of the person and his or her medical history. However, here are the general tests to be performed.",
              respont: "It is usually necessary to do a complete blood count, glycemia, urea, creatinine, coagulation times, typing, pregnancy test, viral tests; hepatitis, HIV, and if there is any thyroid disorder, hormone levels; T3, T4, TSH. Also mandatory is a chest x-ray, electrocardiogram. Cardiovascular and pre-anesthetic evaluation.",
              requeriment: "Requirements",
              questot: "What requirements are recommended before surgeries?",
              respontr:"Psychological stability and good health are essential to be a good candidate.",
              responfo: "In the days, and even weeks, prior to the operation, a series of simple indications must be followed. These are usually supplemented by a list of personal instructions for each individual case.Do not forget to clarify any last minute doubts in order to avoid nerves and questions during the operation. You will also be told the time and place of the operation, as well as if it is necessary to purchase any accessories or clothing for the postoperative period. Leave all papers, clothes and other belongings ready and rest well the night before. It is recommended to use antiseptic soap and prepare the skin with moisturizing cream. Aspirin and other medications with salicylates should be avoided, as well as large meals. It is also essential (and logical) to stop smoking about 6 weeks before the operation and, likewise, not to consume drugs or alcohol.",
              recomen: "We recommend you these places to have your exams done",
              elect: "Electrocardiogram",
              dom: "At home Cost $110.000",
              hosp: "Soma Clinic Cll. 51 # 45-93, Medellín cost $45.000",
              ana: "Complete analysis",
              dates: "Ask for their prices: +57 324 651 5019- E-mail- info@poctlab.com Address- Calle 19a # 44-25, cons. 2114, Torre Médica Salud & Servicios, Ciudad del Río, Medellín.",
              qprice: "Ask about their prices: (604) 444 56 90. 316 403 76 61 (private chat)",
              spe: "Specialists",
              infor: "Today's society must learn to see life from a different point of view, not only focusing on the epidermis and the external appearance of the body, but keeping in mind the important issues that identify us and give us meaning. In surgery, the ethical context establishes that a good act is when its objective is achieved. That is why it is important to choose the right specialist for each patient according to their needs, because for a good qualification the purpose must be well defined without ever forgetting its intention, which is to provide the patient with a better quality of life.",
              doc: "Plastic Surgeon",
              master: "Master in microsurgery",
              exp: "Expert in: Mammoplasty, gynecomastia, liposuction, abdominoplasty.",
              expe: "Expert in: liposculpture, augmentation mammoplasty, rhinoplasty, abdominoplasty",
              medc: "General practition",
              exper: "Expert in: Initial assessment and medical history taking.",
              anes: "Anesthesiologist",
              experi:"Expert in: Loco-regional anesthesia (Intradural / Epidural).",
              der:"Dermatologist",
              expert: "Expert in: acne, skin blemishes, alopecia, hyaluronic acid.",
              experi:"Expert in: botulinum toxin (Botox), hyaluronic acid, biostimulation with radiofrequency, facial rejuvenation.",
              experien: "Expert in: peeling, biostimulation with radiofrequency, cryotherapy, mesotherapy.",
              nurse: "Nurse",
              cuipost: "Expert in: Post-operative care.",
              imagee:"Image",
              namee:"Name",
              price:"Price",
              cant:"Quantity",
              vac:"Empty Cart",
              evw: "Evaluation with general practitioner",
              pric: "Between $700,000,000 - 3'800,000 million Pesos.",
              va:"Evaluation with general practitioner",
              car: "Add To Cart",
              labtest:"Laboratory tests",
              exm: "Between 70,000 and 180,000 Thousand Pesos.",
              lprice: "Between 5'000,000 and 10'000,000 Million Pesos.",
              rnose: "Between 6'500,000 and 14'000,000 Million Pesos.",
              mprice: "Between 6'000,000 and 10'000,000 Million Pesos.",
              serum: "Serum Therapy",
              sprice: "Between 250,000 and 800,000 Pesos.",

            },
          },
          es: {
            translation: {
              inicionav: "Inicio",
              greeting: "Nosotros",
              farewell: "Servicio",
              procedure: "Procedimientos",
              medicalE: "Examenes Médicos",
              specialist: "Especialistas",
              quotation: "Cotización",
              log: "Ingresar",
              esthetic: "Cirugía Estética",
              sugery: "Con el objetivo de generar en las personas una mejor apariencia, aumentar el autoestima y la confianza en sí misma, en Esthetic Healt te brindamos toda la información de los procedimientos que quieras realizarte, conocerás beneficios, especialistas y cotizaciones. Recuerda la importancia de indagar a profundidad sobre el procedimiento a realizar y el profesinal que te prestará el servicio, aquí encuentras una agenda de confianza para que estés seguro que la intervención a realizarte será hecha por los mejores especialistas.",
              dermatology: "Dermatología",
              dermatologyDes: "Especialidad médica destinada al estudio, conocimiento, diagnóstico y tratamiento de todas aquellas patologías o afecciones de la piel. En Esthetic Health encontrarás el enlace a los mejores especialistas para que le regales a tu piel el mejor cuidado, realizando tus procedimientos de la mano con los mejores.",
              recovery: "Recuperación",
              recoveryDes: "Conoce aquí los profesionales que ayudarán a que tu cirugía tenga los mejores cuidados postoperatorios, brindándote la mejor atención para que te recuperes de forma más rápida obteniendo los mejores resultados.",
              contactus: "Contactanos",
              advisor: "Asesores",
              Sponsors: "Patrocinadores",
              ourprogam:"Nuestros programadores",
              registration: "Regístrate",
              gree: "Nosotros somos un equipo de desarrolladores apasionados por la innovación y la búsqueda de un impacto positivo en las personas que necesitan de ayuda para recurrir a servicios seguros, eligiendo lo mejor para ellos. Nuestro propósito con Esthetic Health es lograr tener una plataforma completa donde las personas encuentren y puedan acceder a la información necesaria e importante cuando quieran realizarse una intervención estética o procedimiento dermatológico.",
              cod: "Riwi Coders",
              tel: "Telefono",
              ourservice: "Nuestros servicios",
              ape: "Procedimientos esteticos Medellín",
              ena: "En Esthetic Health te ofrecemos un amplio portafolio de servicios que se van a ajustar a tus necesidades, brindándote la confianza de encontrar el mejor especialista para realizarte tus procedimientos.",
              proceDes: "Te ayudamos a conseguir una cita para valoración inicial con uno de los mejores médicos generales para que puedas conocer tu estado de salud y guiarte en el procedimiento que desees realizarte.",
              medicalDes: "Te brindamos información completa de los exámenes que debes realizarte antes del procedimiento a elegir y sus costos.",
              espeDes: "Te brindamos la mejor información de cirujanos, anestesiologos, terapeutas y enfermeras que cuiden de ti durante todo el proceso.",
              care: "Cuidados",
              mobilization: "1. El paciente debe movilizarse. Para tener un buen post operatorio, debes caminar dentro de tu casa, siempre en compañía de un familiar o enfermera, desde el mismo momento de su egreso de la clínica.",
              hydration: "2. Hay que mantenerse hidratado. Debes tomar agua frecuentemente, y también aromáticas y jugos en agua. Evita el té y el café.",
              diet: "3. Dieta líquida o blanda el primer día. Las primeras 24 después de tu cirugía plástica, debes seguir una dieta a base de consomé, sopas, jugos no ácidos, gelatina y aromáticas.",
              respiratory: "4. Realiza ejercicios respiratorios con incentivador durante 5 minutos continuos, 4 veces al día, durante la primera semana de tu post operatorio.",
              rest: "5. Intenta descansar durante el sueño.",
              medication: "6. Tómate las medicinas. Cumple con la toma de los medicamentos formulados y con los horarios establecidos. Esto es fundamental para garantizar los resultados y disminuir riesgos y posibles complicaciones.",
              dizziness: "7. Al levantarte de la cama, puedes experimentar mareos. En este caso es aconsejable regresar a la cama y acostarse con las piernas elevadas. En pocos minutos te sentirás mejor.",
              bandage: "8. No retires los vendajes o curaciones hasta que tu médico lo autorice.",
              drain: "9. No mojes los drenajes y/o heridas hasta que tu cirujana plástica te lo indique. Evita mojarlos cuando te bañes, y si accidentalmente se llegan a mojar, sécalos bien sin retirar los vendajes o curaciones.",
              sunprotection: "10. Evita la exposición solar del área operada durante los primeros 4 meses de la cirugía.",
              sexualabs: "11. No tengas relaciones sexuales durante el primer mes del post operatorio.",
              safemobi: "12. Desplázate de la forma más cómoda y segura. Evita utilizar la moto o el transporte público.",
              des: "En Esthetic Health encontrarás los mejores profesionales que te ayudarán con tu proceso de recuperación.",
              pie: " Todos los derechos de autor estan reservados a Riwi - 2023.",
              face: "Rostro",
              nose: "Rinoplastia",
              see: "Ver más", 
              biche: "Bichetomia",
              blefaro: "Blefaroplastia",
              lipo: "Liposucción",
              otoplas: "Otoplastia",
              body: "Cuerpo",
              lipo: "Liposucción,",
              lipoEs: "Lipoescultura",
              glu: "Gluteoplastia",
              cirba: "Cirugía bariátrica",
              abdom: "Abdominoplastia",
              sen: "Senos",
              maum: "Mamoplastia aumento",
              maur: "Mamoplastia reducción",
              mast: "Mastopexia",
              breco: "Reconstrucción Mamaria",
              ginecoma: "Ginecomastia",
              dermatological:"Dermatólogicos",
              hyal: "Ácido hialurónico",
              botox: "Botox",
              eare: "Rejuvenecimiento facil",
              peeling: "Peeling",
              acne: "Tratamiento para el acne",
              exapre:"Examenes preoperatorios",
              questo: "¿Cuáles éxamenes se recomiendan antes de las cirugías?",
              respono: "Para los procedimientos que serán realizados bajo anestesia se requiere una serie de análisis preoperatorios, los cuales indicarán al médico posibles problemas que se podrían presentar en la intervención y a su vez determinar los factores de riesgo a prevenir. Los éxamenes siempre deben basarse en la evaluación individual de la persona y sus antecedentes médicos. Sin embargo, te presenteamos los éxamenes generales para realizarte.",
              respont: "Por lo general es necesario hacer hemograma, glicemia, urea, creatinina, tiempos de coagulación, tipificación, prueba de embarazo, pruebas de virales; hepatitis, VIH, y si hay algún trastorno de tiroides, niveles hormonales; T3, T4, TSH. También es mandatorio una radiografía de tórax, electrocardiograma. Evaluación cardiovascular y pre-anestésica.",
              requeriment: "Requisitos",
              questot: "¿Cuáles requisitos se recomiendan antes de las cirugías?",
              respontr: "La estabilidad psicológica y contar con buena salud es esencial, para ser un buen candidato.",
              responfo: "Los días, e incluso semanas, antes de la operación, se deben seguir una serie de indicaciones sencillas. Estas, suelen ir complementadas con una lista de indicaciones personales atendiendo a cada caso particular.No olvides esclarecer todas las dudas de última hora para evitar los nervios y las preguntas durante la operación. También, se te indicarán las horas y el lugar de la intervención, así como, si se requiere la compra de algún accesorio o prenda para el postoperatorio. Deja todos los papeles, ropa y demás enseres preparados y descansa bien la noche antes.Se recomienda emplear jabón antiséptico y preparar la piel con crema hidratante. Se deben evitar las aspirinas y demás medicamentos con salicilatos así como las comidas pesadas. También resulta fundamental (y lógico), dejar de fumar unas 6 semanas antes de la operación y, de igual forma, no consumir drogas ni alcohol.",
              recomen: "Te recomendamos estos lugares para realizarte tus examenes.",
              elect: "Electrocardiograma",
              dom: "A domicilio costo $110.000",
              hosp: "Clinica soma Cll. 51 # 45-93, Medellín Costo $45.000",
              ana: "Analisis completo",
              dates: "Pregunta por sus precios: +57 324 651 5019 E-mail: info@poctlab.com. Dirección: Calle 19a # 44-25, cons. 2114, Torre Médica Salud & Servicios, Ciudad del Río, Medellín.",
              qprice: "Pregunta por sus precios: (604) 444 56 90. 316 403 76 61 (chat particulares)",
              spe: "Especialista",
              infor:"La sociedad actual debe aprender a ver la vida desde un punto de vista diferente, no sólo centrándose en la epidermis y la apariencia externa del cuerpo, sino teniendo presentes las cuestiones importantes que nos identifican y nos dan sentido. En cirugía, el contexto ético establece que un buen acto es cuando se logra su objetivo.Es por eso la importancia de elegir un especialista adecuado para cada paciente según sus necesidades, pues para una buena calificación se debe tener bien definido el propósito sin olvidar nunca su intención, que es brindarle al paciente una mejor calidad de vida.",
              doc: "Cirujano plastico",
              master: "Master en microcirugia",
              exp: "Experto en: Mamoplastia, ginecomastia, liposucción, abdominoplastia",
              expe: "Experto en: lipoescultura, mamoplastia de aumento, rinoplastia, abdominoplastia",
              medc: "Medico general",
              exper: "Experto en: Valoración inicial y realización de historias clínicas.",
              anes: "Anestesiólogo",
              experi: "Experto en: Anestesia loco-regional (Intradural / Epidural).",
              der:"Dermatologa",
              expert:"Experta en: acné, manchas en la piel, alopecia, ácido hialurónico.",
              experi: "Experta en: toxina botulínica (bótox), ácido hialurónico, bioestimulación con radiofrecuencia, rejuvenecimiento facial.",
              experien: "Experto en: peeling, bioestimulación con radiofrecuencia, crioterapia, mesoterapia.",
              nurse: "enfermera",
              cuipost:"Experta en: cuidados post operatorios.",
              imagee:"Imagen",
              namee:"Nombre",
              price:"Precio",
              cant:"cantidad",
              vac: "Vaciar carrito",
              evw: "Valoración con médico general",
              pric: "Entre $700.000 mil - 3'800.000 millones de Pesos.",
              va: "Valoración con médico general",
              car: "Agregar al carrito",
              labtest: "Examenes de laboratorio",
              exm: "Entre 70.000 y 180.000 Mil Pesos.",
              lprice:"Entre los 5'000.000 y 10'000.000 Millones de Pesos.",
              rnose:"Entre los 6'500.000 y los 14'000.000 Millones de Pesos.",
              mprice:"Entre los 6'000.000 y 10'000.000 Millones de Pesos.",
              serum: "Suero terapia",
              sprice: "Entre los 250.000 y 800.000 Mil Pesos.",
            },
          },
        },
      },
      function (err, t) {
        updateContent();
      }
    );

    function updateContent() {
      const elements = document.querySelectorAll(".translate");
      elements.forEach((el) => {
        const key = el.getAttribute("data-i18n");
        el.innerHTML = i18next.t(key);
      });
    }

    window.changeLanguage = function (lng) {
      i18next.changeLanguage(lng, updateContent);
    };
  });
